#! /bin/sh

sxhkd &
#compton --vsync=opengl-swc --backend=glx --shadow-opacity=0 --glx-no-stencil --glx-no-rebind-pixmap &
feh --bg-scale ~/Pictures/nord.png & 
/home/karlc/code/cleanfullscreen/cleanfullscreen &
xscreensaver -no-splash &

bspc monitor eDP-1 -d I II III IV V VI VII VIII IX

bspc config single_monocle 	  true

bspc config automatic_scheme alternate

bspc config border_width         2
bspc config window_gap           20

bspc config -m eDP-1 top_padding          40
bspc config -m eDP-1 bottom_padding       40
bspc config -m eDP-1 left_padding         40
bspc config -m eDP-1 right_padding        40

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
