#! /bin/sh

sxhkd &
#compton --vsync=opengl-swc --backend=glx --shadow-opacity=0 --glx-no-stencil --glx-no-rebind-pixmap &
feh --bg-scale ~/Pictures/nord.png & 
/home/karlc/code/cleanfullscreen/cleanfullscreen &
xscreensaver -no-splash &

bspc monitor eDP-1 -d I II III IV V VI VII VIII IX

bspc config single_monocle 	  true

bspc config automatic_scheme alternate

bspc config border_width         2
bspc config window_gap           20

bspc config -m eDP-1 top_padding          40
bspc config -m eDP-1 bottom_padding       40
bspc config -m eDP-1 left_padding         40
bspc config -m eDP-1 right_padding        40

bspc config split_ratio          0.5
bspc config borderless_monocle   true
#bspc config gapless_monocle      false
#bspc config paddingless_monocle  false

bspc config top_monocle_padding -10
bspc config bottom_monocle_padding -50
bspc config left_monocle_padding -50
bspc config right_monocle_padding -50

# https://www.reddit.com/r/bspwm/comments/fkgc94/monocle_true_transparency_hiding_not_focused_node/ 
#### Transparency hack: works by hiding previous focused nodes
manage_node_transparency () {
  # Store last ids
  PREV_NODE_ID=
  PREV_DESK_ID=
  # On envery focus change
  bspc subscribe node_focus | while read -r _ _ desktop_id node_id; do
    # Set my custom _COMPTON_MONOCLE xprop to 1, meaning active
    xprop -id "$node_id" -f _COMPTON_MONOCLE 32c -set _COMPTON_MONOCLE 1;
    # Check if previous desktop is the same of now (no need to hide when changing desktops)
    if [ "$PREV_DESK_ID" == "$desktop_id" ] && [ "$PREV_NODE_ID" != "$node_id" ]; then
      # Get the layout of the previous node to hide
      PREV_LAYOUT=$(bspc query -T -d "$desktop_id" | jq -r .layout);
      # Hide the previous node only if it was on a monocle desktop
      [ "$PREV_LAYOUT" == "monocle" ] && xprop -id "$PREV_NODE_ID" -f _COMPTON_MONOCLE 32c -set _COMPTON_MONOCLE 0;
    fi
    # Update previous ids
    PREV_NODE_ID=$node_id
    PREV_DESK_ID=$desktop_id
  done

}

#### Manage Desktop Layout Change
manage_desktop_layout () {
  # Subscribe to layout change event
  bspc subscribe desktop_layout | while read -r _ _ desktop_id layout; do
    if [ "$layout" == "tiled" ]; then
      # If tiled set _COMPTON_MONOCLE to all window nodes
      bspc query -N -n .window -d "$desktop_id" | xargs -I % xprop -id % -f _COMPTON_MONOCLE 32c -set _COMPTON_MONOCLE 1;
    else
      # Else, set 0 to all non focused window nodes
      bspc query -N -n .window.!focused -d "$desktop_id" | xargs -I % xprop -id % -f _COMPTON_MONOCLE 32c -set _COMPTON_MONOCLE 0;
    fi
  done
}

manage_node_transparency &
manage_desktop_layout &

